version: 2

sources:
  - name: google_ads
    schema: google_ads
    tables:
      - name: ad_stats
      - name: campaign_history
      - name: ad_group_history
      - name: search_term_keyword_stats
  
  - name: facebooks_ads
    schema: facebooks_ads
    tables:
      - name: basic_ad
      - name: campaign_history
      - name: basic_ad_set

  - name: linkedin_ads
    schema: linkedin_ads
    tables:
      - name: campaign_history
      - name: ad_analytics_by_campaign
      - name: ad_analytics_by_creative
      - name: creative_history
