version: 2

sources:
  - name: google_ads
    schema: google_ads
    tables:
      - name: ad_stats
      - name: campaign_history
      - name: ad_group_history
      - name: search_term_keyword_stats
  
  - name: facebooks_ads
    schema: facebooks_ads
    tables:
      - name: basic_ad
      - name: campaign_history
      - name: basic_ad_set

  - name: linkedin_ads
    schema: linkedin_ads
    tables:
      - name: campaign_history
      - name: ad_analytics_by_campaign
      - name: ad_analytics_by_creative
      - name: creative_history


# models:
#   - name: ad
#     description: "Ad-level data from ad_stats table"
#     columns:
#       - name: ad_id
#         description: "ID of the ad"
#         tests:
#           - not_null
#       - name: campaign_id
#         description: "ID of the campaign"
#       - name: device
#         description: "Device type"
#       - name: impressions
#         description: "Number of impressions"

#   - name: groups
#     description: "Ad group-level performance metrics"
#     columns:
#       - name: id
#         description: "Ad group ID"
#         tests:
#           - not_null

#   - name: campaign
#     description: "Campaign-level metadata from ad_group_history"
#     columns:
#       - name: campaign_id
#         description: "Campaign ID"
#       - name: campaign_name
#         description: "Name of the campaign"

#   - name: google_ads_fact
#     description: "Google Ads unified fact table with calculated metrics"
#     columns:
#       - name: ad_id
#         description: "Unique identifier for ad"
#       - name: ad_group_id
#         description: "Associated ad group ID"
#       - name: campaign_id
#         description: "Associated campaign ID"
#       - name: date
#         description: "Date of performance"
#       - name: device
#         description: "Device type"
#       - name: total_impressions
#         description: "Sum of impressions"
#       - name: total_clicks
#         description: "Sum of clicks"
#       - name: total_spent
#         description: "Total cost (cost_micros / 1M + cost_per_conversion)"
#       - name: ctr
#         description: "Click-through rate"
#       - name: cpc
#         description: "Cost per click"
#       - name: campaign_name
#         description: "Campaign name from ad_group_history"
#       - name: status
#         description: "Campaign status"
